version: "3"

services:
    ots:
        build: .
        ports:
            - 8080:8080
        volumes:
            - ./volumes:/app/volumes
            - ./templates:/app/templates
            - ./static:/app/static 
